### PR TITLE
New Action Syntax Proposal

### PR DESCRIPTION
**Pull request by kenwheeler**
I want to get some feedback on this and foster a little discussion.

I've been having some conversations around how and where to handle async. Historically in McFly I had either written an API module that would make async calls and then call actions when resolved, or use the promise returned in Action Creators (prior to removing them this week in search of a better solution).

We had discussed doing it in the stores, but I'm not sure thats flexible or sustainable enough, particularly if you have an action who's payload is digested in multiple stores.

I discussed providing the dispatcher within actions, but after discussing this with Per, this would add async logic into components that call those actions, and it really doesn't belong there.

This PR is where I ended up, removing the implicit dispatch call, and providing action creators with the dispatch method.

**Old syntax:**

```
biff.createActions({
    actionMethod: function(arg){
        return {
            actionType: 'ACTION_TYPE',
            data: arg
        }
    }
});
```

**New syntax:**

```
biff.createActions({
    actionMethod: function(arg){
        this.dispatch({
            actionType: 'ACTION_TYPE',
            data: arg
        })
    }
});
```

An async call using the new syntax would look like:

```
biff.createActions({
    actionMethod: function(arg){

        var _this = this;

        this.dispatch({
          actionType: 'ACTION_STARTED'
        })

        request
          .get(url)
          .end(function(error, res){
            if(error) {
              _this.dispatch({
                actionType: 'ACTION_ERROR',
                data: error
              })
              return;
            }
            _this.dispatch({
              actionType: 'ACTION_SUCCESS',
              data: res
            })
          })

    }
});
```

Let me know what you guy think. Here are a couple resources to review some of the current flux theory out there right now:

[React Conf Flux Panel](https://www.youtube.com/watch?v=LTj4O7WJJ98)

[Async Requests with React & Flux Revisited ](http://www.code-experience.com/async-requests-with-react-js-and-flux-revisited/) 

[Action Creator Async in NuclearMail by Ian Obermiller](https://github.com/ianobermiller/nuclearmail/blob/master/src/js/ThreadActions.js#L39)

cc: @per-nilsson @eastridge @colinmegill @rgerstenberger @zachhale @paulathevalley

### CODE REVIEW

**Comment by eastridge** [comment]
I like this a lot. The interesting thing though is that then this becomes a pattern and not a library. The Action and ActionFactory class don't really serve any purpose if we merge this PR IMHO. At that point biff is really just about stores right? And FL should blog about how we are doing flux in a certain way.

**Comment by kenwheeler** [comment]
I think the only purpose they serve at this point is:
- They pass in the dispatch method that is specific to the dispatcher instance used when creating them
- Abstraction & structure vs just calling dispatcher.dispatch

**Comment by coopy** [comment]
This looks very promising (pun not intended). I actually like the explicit call to `dispatcher.dispatch()` in the action definition - less magic.

**Comment by eastridge** [comment]
With just a few lines of code for that concern I'd say it's in the uncanney valley though. It should do more or go away entirely. A wrapper around the pattern you show might be useful:

```
    Action.prototype.dispatchPromise = function (actionName, promise) {
      var _this = this;
      this.dispatch({
        actionType: actionName + '_STARTED'
      });
      promise.end(function(error, res){
        if(error) {
          _this.dispatch({
            actionType: actionName + '_ERROR',
            data: error
          })
          return;
        }
        _this.dispatch({
          actionType: actionName + '_SUCCESS',
          data: res
        })
      })  
    };

    biff.createActions({
      actionMethod: function(arg){
        var promise = request.get(url);
        this.dispatchPromise('BOOF', promise);
      }
    });
```

**Comment by kenwheeler** [comment]
I think that would be great. Most of my actions in actual use are not async, hence the previous action helper to make the syntax more terse. Does everyone think the 'started,success,end' flow covers all the bases for handling?

**Comment by kenwheeler** [comment]
Also, this syntax is based around using superagent syntax for requests. Is there an internal standard request lib that is used? Or is it variable?

**Comment by eastridge** [comment]
All that should matter is wether you get a promise back. The ES6 spec calls for `then(callback, failback)` which I _think_ request supports as well.

**Comment by rgerstenberger** [comment]
What would the code look like in a component?

My main use cases:
1. Component fires action, needs to know if in loading state
2. Component fires action, needs to know if action was unsuccessful to show error state
3. Component fires action, needs to know if action was successful to advance UI

**Comment by eastridge** [comment]
To phrase another way: if we don't return a promise from the action creator, how do the loading, success and failure states pass through the store to the component. Are they just different props on items the store?

Also, where should router redirect calls live? I am listening to the completion of the action where?

@kenwheeler @per-nilsson Did we settle on _not_ returning promises from action creators?

**Comment by kenwheeler** [comment]
In a component the action would presumably be triggered by an event, such as:

``` js
var Component = React.createClass({
    handleClick: function(){
        MyActions.action(args)
    },
    render: function() {
        return (
            <button type="button" onClick={this.handleClick}>Click Me</button>
        )
    }
});
```

How the args that are passed are handled would be determined by the method definted when creating the Action Creators via the `createActions` method, as shown in the examples above.

**Comment by eastridge** [comment]
@kenwheeler I think we were writing at the same time =) Check out my questions above.

**Comment by rgerstenberger** [comment]
@kenwheeler So how you handle loading, error, success states are determined by two implementor pieces?
- How you set up your action to take in options/args
- The actual options/args the component passes in

If so, I think we'll be writing a lot of the same boilerplate in every action creator and component.

**Comment by kenwheeler** [comment]
@eastridge typically when the action is fired, in the event of success, the store data would be mutated, a change would be emitted, and the component would react to that event by querying the store for the new data. 

In the event that one wanted to make an optimistic update, the update could be made to component local state via the click handler, at which point the success or fail would mutate the store in order to send back the final pass or fail state.

The only reason I'm wary on promises is because of issues I have had with them swallowing errors. 

Re: routing, there is a lot of discussion around flux driven routing. Here is one example:

https://github.com/rackt/react-router/blob/master/docs/guides/flux.md

**Comment by kenwheeler** [comment]
@rgerstenberger They would be handled in the action creator itself.

``` js
/// How you set up your action to take in options/args

biff.createActions({
    action: function(createArg1, createArg2) {

    }
});

// The actual options/args the component passes in

var Component = React.createClass({
    clickHandle: function(createArg1, createArg2) {
        MyActions.action({
            arg1: createArg1,
            arg2: createArg2
        }
    }
    render: function(){
        return (
            <button onClick={this.clickHandle}>click me</button>
        )
    }
})
```

**Comment by eastridge** [comment]
@kenwheeler I think a complete example of how the loading, error and complete states would pass through all the way to the view through the store would be immensely helpful to the conversation. Perhaps slightly beyond the scope of the PR, but it feels relevant.

**Comment by eastridge** [comment]
Going to hit the road, will not be able to participate in the convo until later today.

**Comment by kenwheeler** [comment]
@eastridge I'll set up a repo tonight/tomorrow using the callback method and the promise method with routing.

**Comment by kenwheeler** [comment]
While sort of orthogonal to this conversation, if anyone wants to take a look at https://github.com/HubSpot/general-store , ping me if you think anything there is worth borrowing. I know we had discussed the other day how unpalatable the switch/if condition in the store callback is, and general-store has a nice model for explicit registration.

**Comment by rgerstenberger** [comment]
With the above I see us writing something like this:

```
biff.createActions({
    action: function(loadingStart, LoadingEnd, error, success) {
        // Wire these args the same way in every action
    }
});


var Component = React.createClass({
    clickHandle: function(createArg1, createArg2) {
        // Wire these options up nearly the same way in every component
        MyActions.action({
            // not sure es6 binds these how I intended
            loadingStart() { this.setState({ loading: true }),
            loadingEnd() { this.setState({ loading: false }),
            error() { this.setState({ dirty: true })},
            success: this.onSuccess,
        });
    },
    onSuccess: function () {
        this.setState({ dirty: false });
        this.props.continue();
    },

    render: function(){
        var loadingIndecator = this.state.loading ? <Loading /> : null;
        var errorIndecator = this.state.diry ? <Dirty /> :  null;

        return (
            <button onClick={this.clickHandle}>click me</button>
            {loadingIndecator}
            {errorIndecator}
        )
    }
```

**Comment by kenwheeler** [comment]
That sort of syntax is probably a lot easier if the async logic is in the action as opposed to the action creator. I'm going to do some mock ups and see how I can meet halfway on that, keeping most logic out of the component, but allowing for local state changes for things like loading.

**Comment by tomatau** [comment]
After talking with many people in the Flux community - They consistently suggesting having one action dispatched per action creator invocation for debugging purposes. So I did some massive refactors to only have one action per action creator and it works really well...

Now, If I need to dispatch that some action has started to display a loading bar - I'm using another action that's invoked from the same place (inside a view) - leaving my core action empty of 'start' logic and more reusable.

I personally find the current action creator syntax incredibly convenient to return an action object or promise. e.g.

``` javascript
let AppAction = flux.createActions({
  startLoading(speed) {
    return {
      actionType: AppConstants.START_LOADING,
      speed: speed
    }
  },
  setLoaderProgress(amount){
    return {
      actionType: AppConstants.SET_PROGRESS,
      amount: amount
    }
  },
```

component

``` javascript
let ContentPreview = React.createClass({
...
  handleAddElement(contentItemElement){
    AppActions.startLoading();
    ContentActions.addAfter(
      this.props.item, element
    ).then(()=>{
      AppActions.setLoaderProgress(100);
    })
  },
```

I can also handle errors in a catch block to display warnings or feedback, add more notification logic that is explicit to the case of the component's button being pressed.

Main reusable action:

``` javascript
let ContentActions = core.flux.createActions({
  addElementAfter(contentItem, element) {
    return duplicateElement(contentItem, element)
      .then((contentItemElements)=>({
        actionType: ContentItemElementConstants.CREATE_ELEMENT,
        contentItemElements: contentItemElements
      }))
  },
```

This has been scaling very well for me - allowing me to have simple actions that utilise helpers and things are very reusable.

I do a lot of booting up my application from localstorage and it would be very difficult and verbose to make use of actions that assumed things like loading progress should be notified.

**Comment by kenwheeler** [comment]
@eastridge I just put together a couple of examples of different ways to handle async & loading states. Everyone can check it out here https://github.com/kenwheeler/FluxExample

``` js
npm install
grunt serve
```

I rolled the actions from scratch on the basis of not having to create separate biff versions.

**Comment by rgerstenberger** [comment]
@kenwheeler Awesome work! I like the version with `loading` and ideally `error` being properties of the store that get set as state on the component. This keeps components "data" driven and agnostic from async requests and action implementation. E.g. `AsyncInAction.js`.

The async could be an implementation of the store instead of the action.

The main use cases I've hit for this:
- Local store state: A component triggers an action and needs to know if the store is in loading state or error state.
- Global store state: A component needs to know any time the store is in loading or error state.

**Comment by kenwheeler** [comment]
@rgerstenberger I've seen it done in both. Most of the time I haven't seen store async triggered by components. I much prefer keeping it on the action side of things, because an action can be digested by multiple stores.

**Comment by eastridge** [comment]
@kenwheeler @rgerstenberger just getting caught up on the conversation here. So from reading the thread and the example it would seem that triggering multiple actions during a network request (success, fail, etc) is what we are settling on? This goes against what tomatau was suggesting. I will say although it's simpler I found it very verbose to implement.

One suggestion I would have is to add loading and error states a normalized API of the store. Don't provide much, but at least set a standard?

**Comment by kenwheeler** [comment]
@eastridge The one thing I disagree with in tomatau's example is the component getting success confirmation from the action itself. I feel like it should be getting confirmation from the store. Having a normalized dirty/clean or success/error right on the store would be helpful, as components that cared to act upon that could retrieve it. 

I don't think we've necessarily settled on an approach, as I'd like to hear some more feedback or concerns in regards to the approaches before deciding.

**Comment by kenwheeler** [comment]
@eastridge Also, to tomatau's point, he might not always need loading notification, so the method where you explicitly dispatch within the action creator would provide that kind of flexibility.

**Comment by eastridge** [comment]
I think we should _not_ return promises from the action creators and that the components should be fully synchronous. I can't remember where we left this discussion, but where would router redirects live? Action creators?

**Comment by eastridge** [comment]
Oh, and not to apply too much pressure but this should be at the top of our list to get done. This impacts multiple projects that are in flight.

**Comment by kenwheeler** [comment]
Ryan Florence provides some suggestions on routing here:

https://github.com/rackt/react-router/issues/380

**Comment by kenwheeler** [comment]
Some additional stuff here https://github.com/rackt/react-router/blob/master/docs/guides/flux.md#accessing-route-and-params-from-action-creators

**Comment by kenwheeler** [comment]
I think action creators is probably where the transitions would best reside

**Comment by rgerstenberger** [comment]
> One suggestion I would have is to add loading and error states a normalized API of the store. 

Agree

> I think we should not return promises from the action creators and that the components should be fully synchronous.

agree

> So from reading the thread and the example it would seem that triggering multiple actions during a network request (success, fail, etc) is what we are settling on?

Disagree

To Ken's point about multiple store's consuming an action, either store update order matters (`waitFor`) or it doesn't. In the `waitFor` case, I think the async should be a store implementation that when it finishes, continues propagating the action to the next store AKA actually waits for the first store.

Using multiple actions that are spawned from an original async action seems messy and problematic to me.

**Comment by kenwheeler** [comment]
What if multiple stores consume the result of the request in the form of a payload? Would each one have to make the same request?

**Comment by rgerstenberger** [comment]
Good point. I'd hope data dependencies would be resolved by case 1 below. If not, really we have two cases:
1. Store 2 needs to wait for store 1 to finish async operation based on action data. (serial store updates)
2. Store 1 and 2 need to wait for same async operation to return data. (parallel store updates)

Open questions: 

In case 1, is store 2 in a loading state while store 1 is loading? What about error state?
In case 2, are both stores in a loading state? How is error state handled in each store?

**Comment by kenwheeler** [comment]
If you were using Dispatcher.waitFor syntax, both would respond to 'ACTION_START', hence both would be loading, provided both had a loading implementation. Store 2 just wouldn't set itself to be loading until Store 1 did. Both would also set error states providing they had error implementations.

**Comment by tomatau** [comment]
@kenwheeler re: confirmation back from action to component through promise - I somewhat agree with you - but this pattern has worked well for me and it never involves sending data back to the component. The only only information sent back is "whether the actionCreator method that it invoked was successful or not". I've found this very preferable to having a store that handles all error payloads which can get very large very fast. This pattern also allows me to see certain flows of events in one place that compose certain general actions such as loading bars and notifications.

re: explicit dispatch calls in action creators - I don't see how this is beneficial other than to remove a simple layer sugar. Conditional return blocks can easily decide on different actions to dispatch. To me- having explicit dispatches makes it more easy to use the 'anti-pattern' of multiple actions per creator (which introduces many debugging complications through the dispatch cycle).

Re: multiple actions per network request - I've never found this necessary - one action is often more than enough to populate all appropriate stores and waitsFor cases are seldom.

I've found myself often having an 'Action Helpers' layer that consists of core action logic that may be reused such as a series of requests combined with localStorage updates. This allows easily for ActionCreators to reuse logic - making it easy to have initialisation actions that often combine ActionHelpers to dispatch a large action to populate most stores on bootstrap or route changes.

I've been also using react-router in production which seems to limit redirects to the component mixins - this has worked ok for me also - they provide nice static methods that can be used for cases of 'WillTransitionTo' and 'WillTransitionFrom' that can defer for a promise responses and redirect appropriately when needed.

**Comment by kenwheeler** [comment]
@tomatau when you're store is notifying the component, how are you discerning which action it originated from?

**Comment by tomatau** [comment]
I submit notifications specific to uses of a certain action - allows me to give more specific feedback when in a certain area of the UI e.g. using a shortcut button might want more feedback than when pressing the button from a main control panel and also I'd not want to have a bunch of notifications spam up when the app boots. 

E.g.

``` javascript
let SomeComponent = React.createClass({
  handleSomething(){
    SomeActions.doSomething().then(
     ()=>{
      NotifcationActions.sendHappy(
'Some text specific to the button being pressed from this component');
    },
    ()=>{
      NotifcationActions.sendSad(
'Oops maybe you used this component incorrectly - try pressing the super magic fix button');
    })
  },
```

My Stores are just a data layer and don't care about how they were populated - my UI just responds to the state they hold and displays accordingly.

Granted - I could put this notification information as a paramter into the `doSomething` call and have the actionCreator dispatch according to whether the message is there or not - but I prefer to keep my actions as small as possible and make components explicit on notifications, loading bars and other UI related actions.

(Alternatively, It could be a nice case to have certain ActionCreators extend from a NotificationActionCreator to reuse the logic of handling notifications - maybe - I'm not 100% on if that would work and could get hairy)

**Comment by kenwheeler** [comment]
Merging this in for Biff

**Pull request merged**
